name: Lets Start DeepanshuRobot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 1356469075]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'DeepanshuRobot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: STD-DEEPANSHU 
          commit_user_email: 102808014+STD_DEEPANSHU@users.noreply.github.com
          commit_author: AnonymousR1026 <102808014+STD-DEEPANSHU@users.noreply.github.com>
